/*Tipo lista produccion*/
INSERT INTO `tipo_lista_produc`(`TIPO_LISTA_ITEMS`, `DETALLE_TIPO_LISTA`) 
VALUES ('Materia Prima','Material utilizado para la produccion de un producto');
INSERT INTO `tipo_lista_produc`(`TIPO_LISTA_ITEMS`, `DETALLE_TIPO_LISTA`) 
VALUES ('Productos Produccion','Productos que son realizados en la empresa');

/*Estado Produccion*/
INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Prepoduccion','El produccto aun no se encuentra en proceso de produccion');

INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Bodega','El producto se encuentra almacenado esperando ingresar a produccion');

INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Produccion','El producto se encuentra en proceso de produccion');

INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Control de calidad','El producto esta en inspeccion de defectos ');

INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Embalado y etiquetado','El producto esta en proceso de embalado y etiquetado para entrega final');

INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Finalizado','El producto esta listo para la venta al cliente');

INSERT INTO `estado_produccion`(`ESTADO_PRODUCCION`, `DETALLE_ESTADO_PRODU`) 
VALUES ('Sin Stock','Este producto se encuentra agotado');

/*Tipo Item*/
INSERT INTO `tipo_item`(`TIPO_ITEM`, `DETALLE_TIPO_ITEM`) 
VALUES ('Materia Prima','Material para produccion');
INSERT INTO `tipo_item`(`TIPO_ITEM`, `DETALLE_TIPO_ITEM`) 
VALUES ('Insumos','Insumos para produccion');
INSERT INTO `tipo_item`(`TIPO_ITEM`, `DETALLE_TIPO_ITEM`) 
VALUES ('Producto','Producto para venta');

/*GRUPO_FINANCIERO*/
INSERT INTO MOVIMIENTO_EMPLEADO (DESCRIPCION_MOVIMIENTO_ENPLEADO,VALOR_MOVIMIENTO_EMPLEADO) VALUES 
('IESS', 9.45);
INSERT INTO INFORME_FINANCIERO (TIPO_INFORME) VALUES 
('Balance General');
INSERT INTO INFORME_FINANCIERO (TIPO_INFORME) VALUES 
('Estado de cuentas');
INSERT INTO DEPARTAMENTO (NOMBRE_DEPARTAMENTO) VALUES 
('Personal Administración');
INSERT INTO DEPARTAMENTO (NOMBRE_DEPARTAMENTO) VALUES 
('Personal Comercial');
INSERT INTO DEPARTAMENTO (NOMBRE_DEPARTAMENTO) VALUES 
('Personal Producción');
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('1','Contador',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('1','Tesorero',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('1','Operador de nómina',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('2','Distribuidor minorista de barrio',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('2','Asesor de ventas',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('2','Transportista',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('3','Operario de producción',2.81);
INSERT INTO CARGO_EMPLEADO (ID_DEPARTAMENTO,DESCRIPCION_CARGO,SUELDO_HORAS_CARGO) VALUES
('3','Gestor de pedidos de producción',2.81);
INSERT INTO ASIENTO (ID_INFORME_FINANCIERO,FECHA_ASIENTO,CODIGO_ASIENTO,DEBE,HABER) VALUES
(1,"2022-01-25","1",0.0,0.0);
INSERT INTO ASIENTO (ID_INFORME_FINANCIERO,FECHA_ASIENTO,CODIGO_ASIENTO,DEBE,HABER) VALUES
(1,"2022-01-25","2",0.0,0.0);
INSERT INTO ASIENTO (ID_INFORME_FINANCIERO,FECHA_ASIENTO,CODIGO_ASIENTO,DEBE,HABER) VALUES
(1,"2022-01-25","3",0.0,0.0);
INSERT INTO ASIENTO (ID_INFORME_FINANCIERO,FECHA_ASIENTO,CODIGO_ASIENTO,DEBE,HABER) VALUES
(2,"2022-01-25","4",0.0,0.0);
INSERT INTO ASIENTO (ID_INFORME_FINANCIERO,FECHA_ASIENTO,CODIGO_ASIENTO,DEBE,HABER) VALUES
(2,"2022-01-25","5",0.0,0.0);
INSERT INTO ASIENTO (ID_INFORME_FINANCIERO,FECHA_ASIENTO,CODIGO_ASIENTO,DEBE,HABER) VALUES
(2,"2022-01-25","6",0.0,0.0);
INSERT INTO CUENTA (CUE_ID_CUENTA,ID_ASIENTO,DESCRIPCION_CUENTA,VALOR_CUENTA) VALUES
(null,1,"Activo",0.0);
INSERT INTO CUENTA (CUE_ID_CUENTA,ID_ASIENTO,DESCRIPCION_CUENTA,VALOR_CUENTA) VALUES
(null,2,"Pasivos",0.0);
INSERT INTO CUENTA (CUE_ID_CUENTA,ID_ASIENTO,DESCRIPCION_CUENTA,VALOR_CUENTA) VALUES
(null,3,"Patrimonio",0.0);
INSERT INTO CUENTA (CUE_ID_CUENTA,ID_ASIENTO,DESCRIPCION_CUENTA,VALOR_CUENTA) VALUES
(null,4,"Ingresos",0.0);
INSERT INTO CUENTA (CUE_ID_CUENTA,ID_ASIENTO,DESCRIPCION_CUENTA,VALOR_CUENTA) VALUES
(null,5,"Costos",0.0);
INSERT INTO CUENTA (CUE_ID_CUENTA,ID_ASIENTO,DESCRIPCION_CUENTA,VALOR_CUENTA) VALUES
(null,6,"Gastos",0.0);


INSERT INTO `empleado`(`ID_CUENTA`, `ID_CARGO_EMPLEADO`, `ID_MOVIMIENTO_EMPLEADO`, `NOMBRE_EMPLEADO`, `APELLIDO_EMPLEADO`,
                       `CEDULA_EMPLEADO`, `HORAS_LABORADAS`, `SUELDO`, `SUELDO_NETO`) 
VALUES (6,8,1,'ELVIS','MONTALUISA','0503408080',40,500,450);

INSERT INTO `lista_items`(`ID_EMPLEADO`, `ID_CUENTA`, `ID_TIPO_LISTA_PRODUC`, `DETALLE_LISTA`, `FECHA_LISTA`, `ESTADO_LISTA`,
                          `DETALLE_ESTADO_LISTA`) 
VALUES (1,5,2,'Productos para llenar el stock','2023-01-26','EN PROCESO','PROCESO DE PRODUCCION');

INSERT INTO `item`(`ID_LISTA_ITEMS`, `ID_ESTADO_PRODUCION`, `ID_TIPO_ITEM`, `CODIGO_ITEM`, `NOMBRE_ITEM`, `FECHA_FABRI_ITEM`,
                   `FECHA1_CADU_ITEM`, `FECHA2_CADU_ITEM`, `LOTE_ITEM`, `CANTIDAD_LOTE_ITEM`, `PRECIO_ITEM`, `PESO_ITEM`,
                   `CONSERVACION_ITEM`, `DETALLE_ITEM`) 
VALUES (1,1,3,'101010','MORTADELA PLUMROSE','','','','','','','','','');

INSERT INTO `item`(`ID_LISTA_ITEMS`, `ID_ESTADO_PRODUCION`, `ID_TIPO_ITEM`, `CODIGO_ITEM`, `NOMBRE_ITEM`, `FECHA_FABRI_ITEM`,
                   `FECHA1_CADU_ITEM`, `FECHA2_CADU_ITEM`, `LOTE_ITEM`, `CANTIDAD_LOTE_ITEM`, `PRECIO_ITEM`, `PESO_ITEM`,
                   `CONSERVACION_ITEM`, `DETALLE_ITEM`) 
VALUES (1,1,3,'101010','MORTADELA PLUMROSE','2023-01-26','2023-02-26','2023-03-26','LT1010',100,1.5,200,'Refrigerado',
        'Linea Diaria');

/*Consulta productos terminados para ventas
SELECT ITEM.ID_ITEM, ITEM.ID_LISTA_ITEMS, ITEM.ID_ESTADO_PRODUCION, ITEM.ID_TIPO_ITEM, ITEM.CODIGO_ITEM, ITEM.NOMBRE_ITEM,
ITEM.FECHA_FABRI_ITEM, ITEM.FECHA1_CADU_ITEM, ITEM.FECHA2_CADU_ITEM, ITEM.LOTE_ITEM, ITEM.CANTIDAD_LOTE_ITEM, ITEM.PRECIO_ITEM,
ITEM.PESO_ITEM, ITEM.CONSERVACION_ITEM, ITEM.DETALLE_ITEM FROM `item`,`tipo_item`,`estado_produccion` 
WHERE item.ID_ESTADO_PRODUCION=estado_produccion.ID_ESTADO_PRODUCCION AND item.ID_TIPO_ITEM=tipo_item.ID_TIPO_ITEM AND
tipo_item.TIPO_ITEM='Producto' AND estado_produccion.ESTADO_PRODUCCION='Finalizado';*/

CREATE PROCEDURE LIST_PRODUCTOS()
SELECT ITEM.ID_ITEM, ITEM.ID_LISTA_ITEMS, ITEM.ID_ESTADO_PRODUCION, ITEM.ID_TIPO_ITEM, ITEM.CODIGO_ITEM, ITEM.NOMBRE_ITEM,
ITEM.FECHA_FABRI_ITEM, ITEM.FECHA1_CADU_ITEM, ITEM.FECHA2_CADU_ITEM, ITEM.LOTE_ITEM, ITEM.CANTIDAD_LOTE_ITEM, ITEM.PRECIO_ITEM,
ITEM.PESO_ITEM, ITEM.CONSERVACION_ITEM, ITEM.DETALLE_ITEM FROM item,tipo_item,estado_produccion 
WHERE item.ID_ESTADO_PRODUCION=estado_produccion.ID_ESTADO_PRODUCCION AND item.ID_TIPO_ITEM=tipo_item.ID_TIPO_ITEM AND
tipo_item.TIPO_ITEM='Producto' AND estado_produccion.ESTADO_PRODUCCION='Finalizado';

